routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
use Illuminate\Http\RedirectResponse;

// Routes within this group will have access to sessions and  csrf protection.
// Setup routes for login and registration

Route::group(['middleware' => ['web']], function () {      
      Auth::routes();

      Route::get('/', function () {
            // Check if customer is logged in.
            if (Auth::check()) {
                  // If redirect to the orders pages
                  return Redirect::route('orders.index');
            } else {
                  // Orderwise take them to the landing page.
                  return view('landing');
            }
      });

      Route::group(['middleware' => ['auth']], function () {

            // Register controllers to models.
            Route::resource('orders', 'OrderController');
            Route::resource('customers', 'CustomerController');
            Route::resource('addresses', 'AddressController');

            // A route to display a list of outstanding orders.
            Route::get('customers/{customer}/orders', 'CustomerController@getOrders')->name('customer.orders');

            // A route for customer to add new cards.
            Route::post('customers/{customer}/card/add', 'CustomerController@addNewCard')->name('customer.addcard'); 
            // A route to delete a card
            Route::delete('customers/{customer}/card/delete', 'CustomerController@deleteCard')->name('customer.deletecard'); 

            // A route for customer to add new order to their cart.
            Route::post('customers/{customer}/cart/add/order/{order}', 'CustomerController@addToCart')->name('customer.addtocart');
           // A route for customer to remove an order from their cart.
            Route::get('customers/{customer}/cart/remove/order/{order}', 'CustomerController@removeFromCart')->name('customer.removefromcart');
            // A route for customer to update an order within their cart
            Route::get('customers/{customer}/cart/edit/order/{order}', 'CustomerController@editFromCart')->name('customer.editfromcart');;

            // A route for customer to make an address a primary.
            Route::post('customers/{customer}/address/{address}/make/primary', 'CustomerController@makePrimaryAddress')->name('address.makeprimary');
            // A route for customer to change their primary address.
            Route::post('customers/{customer}/card/{card}/make/primary', 'CustomerController@makePrimaryCard')->name('card.makeprimary');

            // A route for customer to make an order and take payment.
            Route::get('csutomers/{customer}/make/order', 'CustomerController@makeOrder')->name('customer.makeorder');

      });
});

resources/views/widgets/modal/addCard.blade.php
<div class="modal fade" id="addCard">
      <div class="modal-dialog">
            <div class="modal-content">
                  <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Add New Card</h4>
                  </div>
                  <!-- Modal Body -->
                  <div class="modal-body">
                        <form action="{{ route('customer.addcard', [ Auth::user()->id ]) }}" method="POST" class="form-horizontal" id="add-card-form" role="form">
                              {{ csrf_field() }}
                              <div class="form-group">
                                    <label class="col-md-4 control-label" for="name_on_card">Name on Card</label>
                                    <div class="col-md-6">
                                          <input class="form-control" type="text" name="name_on_card" placeholder="Card Holder's Name">
                                    </div>
                              </div>
                              <div class="form-group">
                                    <label class="col-md-4 control-label" for="number">Card Number</label>
                                    <div class="col-md-6">
                                          <input class="form-control" type="text" name="number" placeholder="Debit/Credit Card Number" maxlength="19">
                                    </div>
                              </div>
                              <div class="form-group">
                                    <label class="col-md-4 control-label" for="expiry_month">Expiration Date</label>
                                    <div class="col-md-3">
                                          <select class="form-control" name="expiry_month" id="expiry_month">
                                                 <option>Month</option>
                                                 <option value="01">Jan (01)</option>
                                                 <option value="02">Feb (02)</option>
                                                 <option value="03">Mar (03)</option>
                                                 <option value="04">Apr (04)</option>
                                                 <option value="05">May (05)</option>
                                                 <option value="06">June (06)</option>
                                                 <option value="07">July (07)</option>
                                                 <option value="08">Aug (08)</option>
                                                 <option value="09">Sep (09)</option>
                                                 <option value="10">Oct (10)</option>
                                                 <option value="11">Nov (11)</option>
                                                 <option value="12">Dec (12)</option>
                                          </select>
                                    </div>
                                    <div class="col-md-3">
                                          <select class="form-control" name="expiry_year" id="expiry-year">
                                                <option value="2013">2013</option>
                                                <option value="2014">2014</option>
                                                <option value="2015">2015</option>
                                                <option value="2016">2016</option>
                                                <option value="2017">2017</option>
                                                <option value="2018">2018</option>
                                                <option value="2019">2019</option>
                                                <option value="2020">2020</option>
                                                <option value="2021">2021</option>
                                                <option value="2022">2022</option>
                                                <option value="2023">2023</option>
                                          </select>
                                    </div>
                              </div>
                        </form>
                  </div>
                  <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-primary" name="Add" onclick="document.getElementById('add-card-form').submit();">
                  </div>
            </div>
      </div>
</div>

resources/views/widgets/modal/addaddress.blade.php
<div class="modal fade" id="add-address">
      <div class="modal-dialog">
            <div class="modal-content">
                  <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Add New Address</h4>
                  </div>
                  <!-- Modal Body -->
                  <div class="modal-body">
                        <form action="{{ route('addresses.store') }}" method="POST" class="form-horizontal" id="add-address-form" role="form">
                              {{ csrf_field() }}
                              <div class="form-group">
                                    <label class="col-md-4 control-label" for="number">Address Line 1</label>
                                    <div class="col-md-6">
                                          <input class="form-control" type="text" name="address_line_1" placeholder="" required autofocus>
                                    </div>
                              </div>
                              <div class="form-group">
                                    <label class="col-md-4 control-label" for="number">Address Line 2</label>
                                    <div class="col-md-6">
                                          <input class="form-control" type="text" name="address_line_2" placeholder="">
                                    </div>
                              </div>
                              <div class="form-group">
                                    <label class="col-md-4 control-label" for="number">Town / City</label>
                                    <div class="col-md-6">
                                          <input class="form-control" type="text" name="town_city" placeholder="" required>
                                    </div>
                              </div>
                              <div class="form-group">
                                    <label class="col-md-4 control-label" for="number">County</label>
                                    <div class="col-md-6">
                                          <input class="form-control" type="text" name="county" placeholder="" required>
                                    </div>
                              </div>
                              <div class="form-group">
                                    <label class="col-md-4 control-label" for="number">Postcode</label>
                                    <div class="col-md-6">
                                          <input class="form-control" type="text" name="postcode" placeholder="" required>
                                    </div>
                              </div>
                        </form>
                  </div>
                  <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-primary" name="Add" onclick="document.getElementById('add-address-form').submit();">
                  </div>
            </div>
      </div>
</div>